// internal/proto/ui.proto
// This schema defines the gRPC contract between the FlareGo gateway and the UI.
// The protocol is designed for real-time streaming of flamegraph data to the UI.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ui.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_ui_proto protoreflect.FileDescriptor

const file_ui_proto_rawDesc = "" +
	"\n" +
	"\bui.proto\x12\aagentpb\x1a\x1bgoogle/protobuf/empty.proto\x1a\fcommon.proto2T\n" +
	"\tUIService\x12G\n" +
	"\x11StreamFlamegraphs\x12\x16.google.protobuf.Empty\x1a\x18.agentpb.FlamegraphChunk0\x01B2Z0github.com/Voskan/flarego/internal/proto;agentpbb\x06proto3"

var file_ui_proto_goTypes = []any{
	(*emptypb.Empty)(nil),   // 0: google.protobuf.Empty
	(*FlamegraphChunk)(nil), // 1: agentpb.FlamegraphChunk
}
var file_ui_proto_depIdxs = []int32{
	0, // 0: agentpb.UIService.StreamFlamegraphs:input_type -> google.protobuf.Empty
	1, // 1: agentpb.UIService.StreamFlamegraphs:output_type -> agentpb.FlamegraphChunk
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ui_proto_init() }
func file_ui_proto_init() {
	if File_ui_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ui_proto_rawDesc), len(file_ui_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ui_proto_goTypes,
		DependencyIndexes: file_ui_proto_depIdxs,
	}.Build()
	File_ui_proto = out.File
	file_ui_proto_goTypes = nil
	file_ui_proto_depIdxs = nil
}
