version: 2

project_name: flarego

builds:
  - id: flarego
    main: ./cmd/flarego/main.go
    binary: flarego
    flags:
      - -tags=cli
    goos:
      - linux
      - windows
    goarch:
      - arm64
      - arm
    env:
      - GOARM=7
  - id: flarego-agent
    main: ./cmd/flarego-agent/main.go
    binary: flarego-agent
  - id: flarego-gateway
    main: ./cmd/flarego-gateway/main.go
    binary: flarego-gateway

artifacts:
  builds:
    ids: [flarego, flarego-agent, flarego-gateway]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
