name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Build and Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go 1.24
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install UI dependencies
        run: npm ci
        working-directory: web
      - name: Build UI assets
        run: npm run build
        working-directory: web

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" \
            | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Run Go tests with coverage
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out

      - name: E2E smoke test
        run: |
          docker compose -f deployments/docker-compose.yaml up -d
          sleep 20
          curl -f http://localhost:8080/metrics
          curl -f http://localhost:8081/health

      - name: Generate CHANGELOG
        run: |
          npx conventional-changelog-cli -p angular -i CHANGELOG.md -s -r 1

      # npm publish (если webcomponent появится)
      # - name: Publish WebComponent to npm
      #   if: startsWith(github.ref, 'refs/tags/')
      #   run: |
      #     cd web
      #     npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
